name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

env:
  NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16,18]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v1

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-test-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Build
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
