name: Test - Coverage

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  on_quality_checks:
    name: Generate & Upload to codecov
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [ 18 ]

    steps:
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Generate coverage
        run: pnpm test:coverage

      - name: Publish coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
